import type { Organization, Transformer, Alarm, AuditLog, PlatformStats, TrendPoint } from '@/types'

function generateHistory(baseValue: number, variance: number, points: number = 96): TrendPoint[] {
  const history: TrendPoint[] = []
  const now = new Date()
  let current = baseValue

  for (let i = points - 1; i >= 0; i--) {
    const time = new Date(now.getTime() - i * 15 * 60 * 1000)
    current = current + (Math.random() - 0.5) * variance
    current = Math.max(baseValue * 0.8, Math.min(baseValue * 1.2, current))
    history.push({
      time: time.toISOString(),
      value: parseFloat(current.toFixed(2)),
    })
  }
  return history
}

export const organizations: Organization[] = [
  {
    id: 'org-1',
    name: 'KMUTT University',
    type: 'Educational',
    country: 'Thailand',
    city: 'Bangkok',
    lat: 13.6512,
    lng: 100.4964,
    transformerCount: 5,
    status: 'active',
    licenseTier: 'enterprise',
    contactEmail: 'facilities@kmutt.ac.th',
    createdAt: '2022-01-15',
    platforms: [
      {
        platformId: 'eternity',
        platformName: 'ETERNITY',
        licensed: true,
        features: [
          { id: 'f1', name: 'Digital Twin Visualization', enabled: true, category: 'core' },
          { id: 'f2', name: 'Real-time Telemetry', enabled: true, category: 'core' },
          { id: 'f3', name: 'AI Predictive Diagnostics', enabled: true, category: 'ai' },
          { id: 'f4', name: 'Historical Analytics', enabled: true, category: 'analytics' },
          { id: 'f5', name: 'Report Generation', enabled: true, category: 'reporting' },
        ],
      },
      {
        platformId: 'carbonbox',
        platformName: 'CarbonBOX',
        licensed: true,
        features: [
          { id: 'f6', name: 'Emission Tracking', enabled: true, category: 'carbon' },
          { id: 'f7', name: 'Compliance Reporting', enabled: true, category: 'carbon' },
          { id: 'f8', name: 'Carbon Credit Marketplace', enabled: false, category: 'carbon' },
        ],
      },
      {
        platformId: 'bloodbox',
        platformName: 'BloodBOX',
        licensed: false,
        features: [
          { id: 'f9', name: 'IoT Sensor Integration', enabled: false, category: 'iot' },
          { id: 'f10', name: 'API Integration', enabled: false, category: 'api' },
        ],
      },
    ],
  },
  {
    id: 'org-2',
    name: 'Factory Alpha Industries',
    type: 'Manufacturing',
    country: 'Thailand',
    city: 'Chonburi',
    lat: 13.3611,
    lng: 100.9847,
    transformerCount: 5,
    status: 'active',
    licenseTier: 'professional',
    contactEmail: 'ops@factory-alpha.com',
    createdAt: '2021-08-20',
    platforms: [
      {
        platformId: 'eternity',
        platformName: 'ETERNITY',
        licensed: true,
        features: [
          { id: 'f1', name: 'Digital Twin Visualization', enabled: true, category: 'core' },
          { id: 'f2', name: 'Real-time Telemetry', enabled: true, category: 'core' },
          { id: 'f3', name: 'AI Predictive Diagnostics', enabled: false, category: 'ai' },
          { id: 'f4', name: 'Historical Analytics', enabled: true, category: 'analytics' },
          { id: 'f5', name: 'Report Generation', enabled: true, category: 'reporting' },
        ],
      },
      {
        platformId: 'carbonbox',
        platformName: 'CarbonBOX',
        licensed: false,
        features: [
          { id: 'f6', name: 'Emission Tracking', enabled: false, category: 'carbon' },
          { id: 'f7', name: 'Compliance Reporting', enabled: false, category: 'carbon' },
          { id: 'f8', name: 'Carbon Credit Marketplace', enabled: false, category: 'carbon' },
        ],
      },
      {
        platformId: 'bloodbox',
        platformName: 'BloodBOX',
        licensed: true,
        features: [
          { id: 'f9', name: 'IoT Sensor Integration', enabled: true, category: 'iot' },
          { id: 'f10', name: 'API Integration', enabled: true, category: 'api' },
        ],
      },
    ],
  },
  {
    id: 'org-3',
    name: 'Industrial Corp Ltd',
    type: 'Industrial',
    country: 'Singapore',
    city: 'Singapore',
    lat: 1.3521,
    lng: 103.8198,
    transformerCount: 5,
    status: 'active',
    licenseTier: 'enterprise',
    contactEmail: 'systems@industrial-corp.sg',
    createdAt: '2020-03-10',
    platforms: [
      {
        platformId: 'eternity',
        platformName: 'ETERNITY',
        licensed: true,
        features: [
          { id: 'f1', name: 'Digital Twin Visualization', enabled: true, category: 'core' },
          { id: 'f2', name: 'Real-time Telemetry', enabled: true, category: 'core' },
          { id: 'f3', name: 'AI Predictive Diagnostics', enabled: true, category: 'ai' },
          { id: 'f4', name: 'Historical Analytics', enabled: true, category: 'analytics' },
          { id: 'f5', name: 'Report Generation', enabled: true, category: 'reporting' },
        ],
      },
      {
        platformId: 'carbonbox',
        platformName: 'CarbonBOX',
        licensed: true,
        features: [
          { id: 'f6', name: 'Emission Tracking', enabled: true, category: 'carbon' },
          { id: 'f7', name: 'Compliance Reporting', enabled: true, category: 'carbon' },
          { id: 'f8', name: 'Carbon Credit Marketplace', enabled: true, category: 'carbon' },
        ],
      },
      {
        platformId: 'bloodbox',
        platformName: 'BloodBOX',
        licensed: true,
        features: [
          { id: 'f9', name: 'IoT Sensor Integration', enabled: true, category: 'iot' },
          { id: 'f10', name: 'API Integration', enabled: true, category: 'api' },
        ],
      },
    ],
  },
]

function makeTransformer(id: string, name: string, orgId: string, location: string, lat: number, lng: number, status: 'NORMAL' | 'WARNING' | 'CRITICAL', healthIndex: number): Transformer {
  const isWarning = status === 'WARNING'
  const isCritical = status === 'CRITICAL'

  return {
    id,
    name,
    orgId,
    location,
    lat,
    lng,
    status,
    healthIndex,
    kva: [1000, 1500, 2000, 2500, 3000][Math.floor(Math.random() * 5)],
    voltage: ['11kV/0.4kV', '22kV/0.4kV', '33kV/11kV', '115kV/22kV'][Math.floor(Math.random() * 4)],
    manufacturer: ['ABB', 'Siemens', 'Schneider Electric', 'GE', 'Mitsubishi'][Math.floor(Math.random() * 5)],
    installDate: `201${Math.floor(Math.random() * 9)}-0${Math.floor(Math.random() * 9) + 1}-15`,
    model: `TR-${Math.floor(Math.random() * 9000) + 1000}`,
    serialNumber: `SN${Math.floor(Math.random() * 900000) + 100000}`,
    lastUpdated: new Date().toISOString(),
    sensors: {
      oilTemperature: {
        value: isCritical ? 92 : isWarning ? 82 : 68.4,
        unit: '°C',
        status: isCritical ? 'CRITICAL' : isWarning ? 'WARNING' : 'NORMAL',
        min: 45,
        max: 105,
        threshold: { warning: 80, critical: 95 },
        trend: isWarning ? 'up' : 'stable',
        delta: isWarning ? 2.3 : -0.5,
        history: generateHistory(isCritical ? 92 : isWarning ? 82 : 68, isCritical ? 4 : 3),
      },
      hydrogen: {
        value: isCritical ? 210 : isWarning ? 145 : 120,
        unit: 'ppm',
        status: isCritical ? 'CRITICAL' : isWarning ? 'WARNING' : 'NORMAL',
        min: 0,
        max: 500,
        threshold: { warning: 150, critical: 300 },
        trend: isWarning ? 'up' : 'stable',
        delta: isWarning ? 8.2 : 1.1,
        history: generateHistory(isCritical ? 210 : isWarning ? 145 : 120, 15),
      },
      moisture: {
        value: isCritical ? 35 : isWarning ? 28 : 18,
        unit: 'ppm',
        status: isCritical ? 'CRITICAL' : isWarning ? 'WARNING' : 'NORMAL',
        min: 0,
        max: 50,
        threshold: { warning: 25, critical: 35 },
        trend: 'stable',
        delta: 0.2,
        history: generateHistory(isCritical ? 35 : isWarning ? 28 : 18, 2),
      },
      oilLevel: {
        value: isCritical ? 55 : isWarning ? 65 : 78,
        unit: '%',
        status: isCritical ? 'CRITICAL' : isWarning ? 'WARNING' : 'NORMAL',
        min: 0,
        max: 100,
        threshold: { warning: 70, critical: 60 },
        trend: isWarning ? 'down' : 'stable',
        delta: isWarning ? -1.5 : 0,
        history: generateHistory(isCritical ? 55 : isWarning ? 65 : 78, 2),
      },
      load: {
        value: isCritical ? 95 : isWarning ? 85 : 65,
        unit: '%',
        status: isCritical ? 'CRITICAL' : isWarning ? 'WARNING' : 'NORMAL',
        min: 0,
        max: 100,
        threshold: { warning: 80, critical: 95 },
        trend: isWarning ? 'up' : 'stable',
        delta: isWarning ? 3.1 : -1.2,
        history: generateHistory(isCritical ? 95 : isWarning ? 85 : 65, 5),
      },
      ambientTemperature: {
        value: 32,
        unit: '°C',
        status: 'NORMAL',
        min: 10,
        max: 50,
        threshold: { warning: 40, critical: 50 },
        trend: 'stable',
        delta: 0.5,
        history: generateHistory(32, 2),
      },
    },
  }
}

export const transformers: Transformer[] = [
  makeTransformer('t1', 'TR-001', 'org-1', 'Building A - Main Substation', 13.6512, 100.4960, 'NORMAL', 92),
  makeTransformer('t2', 'TR-002', 'org-1', 'Building B - Distribution', 13.6515, 100.4965, 'WARNING', 73),
  makeTransformer('t3', 'TR-003', 'org-1', 'Building C - Lab Power', 13.6508, 100.4970, 'NORMAL', 88),
  makeTransformer('t4', 'TR-004', 'org-1', 'Campus North Gate', 13.6520, 100.4955, 'CRITICAL', 45),
  makeTransformer('t5', 'TR-005', 'org-1', 'Data Center UPS', 13.6505, 100.4975, 'NORMAL', 96),
  makeTransformer('t6', 'TR-006', 'org-2', 'Production Line A', 13.3611, 100.9840, 'NORMAL', 84),
  makeTransformer('t7', 'TR-007', 'org-2', 'Production Line B', 13.3615, 100.9850, 'WARNING', 68),
  makeTransformer('t8', 'TR-008', 'org-2', 'Warehouse Power', 13.3605, 100.9845, 'NORMAL', 91),
  makeTransformer('t9', 'TR-009', 'org-2', 'Office Complex', 13.3620, 100.9835, 'NORMAL', 87),
  makeTransformer('t10', 'TR-010', 'org-2', 'Utility Room', 13.3600, 100.9855, 'NORMAL', 79),
  makeTransformer('t11', 'TR-011', 'org-3', 'Main Grid Substation', 1.3521, 103.8190, 'NORMAL', 94),
  makeTransformer('t12', 'TR-012', 'org-3', 'Plant 1 - HV Section', 1.3525, 103.8200, 'WARNING', 71),
  makeTransformer('t13', 'TR-013', 'org-3', 'Plant 2 - Distribution', 1.3515, 103.8195, 'NORMAL', 89),
  makeTransformer('t14', 'TR-014', 'org-3', 'Control Room Power', 1.3530, 103.8185, 'NORMAL', 82),
  makeTransformer('t15', 'TR-015', 'org-3', 'Emergency Backup', 1.3510, 103.8205, 'NORMAL', 97),
]

export const alarms: Alarm[] = [
  {
    id: 'a1',
    transformerId: 't4',
    transformerName: 'TR-004',
    orgId: 'org-1',
    severity: 'CRITICAL',
    message: 'Oil Temperature exceeded critical threshold (92.1°C > 95°C)',
    sensor: 'Oil Temperature',
    value: 92.1,
    unit: '°C',
    threshold: 95,
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'a2',
    transformerId: 't4',
    transformerName: 'TR-004',
    orgId: 'org-1',
    severity: 'CRITICAL',
    message: 'Oil Level critically low (55% < 60%)',
    sensor: 'Oil Level',
    value: 55,
    unit: '%',
    threshold: 60,
    timestamp: new Date(Date.now() - 22 * 60000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'a3',
    transformerId: 't2',
    transformerName: 'TR-002',
    orgId: 'org-1',
    severity: 'WARNING',
    message: 'Hydrogen gas concentration elevated (145 ppm > 150 ppm warning)',
    sensor: 'Hydrogen H2',
    value: 145,
    unit: 'ppm',
    threshold: 150,
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'admin',
    acknowledgedAt: new Date(Date.now() - 30 * 60000).toISOString(),
  },
  {
    id: 'a4',
    transformerId: 't7',
    transformerName: 'TR-007',
    orgId: 'org-2',
    severity: 'WARNING',
    message: 'Load approaching maximum rated capacity (85%)',
    sensor: 'Load',
    value: 85,
    unit: '%',
    threshold: 80,
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'a5',
    transformerId: 't12',
    transformerName: 'TR-012',
    orgId: 'org-3',
    severity: 'WARNING',
    message: 'Moisture content elevated in transformer oil (28 ppm > 25 ppm)',
    sensor: 'Moisture',
    value: 28,
    unit: 'ppm',
    threshold: 25,
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'a6',
    transformerId: 't1',
    transformerName: 'TR-001',
    orgId: 'org-1',
    severity: 'INFO',
    message: 'Scheduled maintenance due in 7 days',
    sensor: 'System',
    value: 0,
    unit: '',
    threshold: 0,
    timestamp: new Date(Date.now() - 6 * 3600000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'admin',
    acknowledgedAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'a7',
    transformerId: 't4',
    transformerName: 'TR-004',
    orgId: 'org-1',
    severity: 'CRITICAL',
    message: 'Hydrogen concentration critical level detected (210 ppm > 300 ppm threshold)',
    sensor: 'Hydrogen H2',
    value: 210,
    unit: 'ppm',
    threshold: 300,
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'a8',
    transformerId: 't2',
    transformerName: 'TR-002',
    orgId: 'org-1',
    severity: 'WARNING',
    message: 'Oil temperature rising trend detected over last 2 hours',
    sensor: 'Oil Temperature',
    value: 82,
    unit: '°C',
    threshold: 80,
    timestamp: new Date(Date.now() - 90 * 60000).toISOString(),
    acknowledged: false,
  },
  {
    id: 'a9',
    transformerId: 't6',
    transformerName: 'TR-006',
    orgId: 'org-2',
    severity: 'INFO',
    message: 'Communication signal strength reduced - check antenna',
    sensor: 'System',
    value: 0,
    unit: '',
    threshold: 0,
    timestamp: new Date(Date.now() - 4 * 3600000).toISOString(),
    acknowledged: true,
    acknowledgedBy: 'ops_team',
    acknowledgedAt: new Date(Date.now() - 3.5 * 3600000).toISOString(),
  },
  {
    id: 'a10',
    transformerId: 't7',
    transformerName: 'TR-007',
    orgId: 'org-2',
    severity: 'WARNING',
    message: 'Oil temperature above warning threshold (82°C > 80°C)',
    sensor: 'Oil Temperature',
    value: 82,
    unit: '°C',
    threshold: 80,
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    acknowledged: false,
  },
]

export const auditLogs: AuditLog[] = [
  {
    id: 'al1',
    actor: 'superadmin',
    action: 'Updated entitlement',
    target: 'KMUTT University - AI Diagnostics',
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    ipAddress: '192.168.1.1',
    status: 'success',
  },
  {
    id: 'al2',
    actor: 'superadmin',
    action: 'Created organization',
    target: 'New Factory Ltd',
    timestamp: new Date(Date.now() - 2 * 3600000).toISOString(),
    ipAddress: '192.168.1.1',
    status: 'success',
  },
  {
    id: 'al3',
    actor: 'admin@org-2',
    action: 'Acknowledged alarm',
    target: 'TR-007 - Load Warning',
    timestamp: new Date(Date.now() - 3 * 3600000).toISOString(),
    ipAddress: '10.0.0.45',
    status: 'success',
  },
  {
    id: 'al4',
    actor: 'unknown',
    action: 'Login attempt failed',
    target: 'superadmin account',
    timestamp: new Date(Date.now() - 5 * 3600000).toISOString(),
    ipAddress: '203.55.12.88',
    status: 'failure',
  },
  {
    id: 'al5',
    actor: 'superadmin',
    action: 'Deployed platform update',
    target: 'ETERNITY v2.4.1',
    timestamp: new Date(Date.now() - 8 * 3600000).toISOString(),
    ipAddress: '192.168.1.1',
    status: 'success',
  },
  {
    id: 'al6',
    actor: 'admin@org-3',
    action: 'Generated report',
    target: 'TR-011 Monthly Report',
    timestamp: new Date(Date.now() - 12 * 3600000).toISOString(),
    ipAddress: '10.0.1.22',
    status: 'success',
  },
  {
    id: 'al7',
    actor: 'superadmin',
    action: 'Modified license tier',
    target: 'Factory Alpha - Professional',
    timestamp: new Date(Date.now() - 24 * 3600000).toISOString(),
    ipAddress: '192.168.1.1',
    status: 'success',
  },
]

export const platformStats: PlatformStats = {
  totalOrganizations: 124,
  activeTransformers: 4247,
  dataVolume: '4.2 PB',
  uptime: 99.97,
  activeAlarms: 23,
  criticalAlarms: 4,
}
