apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend.yaml
  - frontend-app.yaml
  - ai-agents.yaml
  - monitoring-stack.yaml
  - mosquitto.yaml
  - mysql.yaml
  - node-red.yaml
  - phpmyadmin.yaml
  - ai-agents-monitor.yaml
  - airflow.yaml
  - data-bridge-infra.yaml
  - network-policy.yaml
