apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: carbon-credit-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://gitlab.com/narongwile/carbon-credit-platform.git
    targetRevision: main
    path: infra/k8s/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: carbon-credit
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
