#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# NO LONGER PART OF THE DEPLOY PATH. The migration Job used to mount the SQL as
# a ConfigMap; it now runs the migrate-service image, which ships backend/sql/
# beside the dist/ that reads it (backend/Dockerfile: COPY sql ./sql), so the
# runner and the schema cannot drift and nothing has to be regenerated by hand
# on every migrate-vN.sql. Kept only for reviving the mount-a-ConfigMap approach
# or for feeding a plain mysql client by hand.
#
# Regenerate the mysql-migrations ConfigMap from backend/sql/*.sql.
#
# The migration Job used to `git clone` this repository at run time. That put a
# public-internet round trip on the critical path of every ArgoCD sync: if
# egress was blocked, gitlab.com was slow, or the branch moved, the clone hung
# and the Sync hook never completed — which stalls the ENTIRE application,
# because nothing else applies until the hook reports.
#
# 47KB of SQL fits in a ConfigMap with room to spare, so the files now ship with
# the manifests and the Job only talks to MySQL.
#
# Usage: infra/scripts/sync-sql-configmap.sh /path/to/backend/sql
# ---------------------------------------------------------------------------
set -euo pipefail
SRC="${1:?usage: sync-sql-configmap.sh <backend/sql dir>}"
# Writes where the caller asks, NOT into the deploy overlay.
#
# It used to default to overlays/uat/mysql-migrations-configmap.yaml. That put a
# 2,500-line file titled "SQL shipped to the mysql-auto-migrate Job" inside the
# directory ArgoCD renders — while the overlay's kustomization.yaml does not
# list it, nothing mounts it, and both the Job and the kustomization carry
# comments saying the ConfigMap was deliberately removed because the SQL now
# ships inside the image. A CI commit then began "syncing" that file, which is
# how a decoy becomes load-bearing in someone's head: the next person adds a
# migration, updates the ConfigMap, and it silently never runs.
#
# Regenerating is still fine — reviving the mount approach, or feeding a plain
# mysql client — but the output has to be somewhere that cannot be mistaken for
# the deploy path.
OUT="${2:-}"
if [ -z "$OUT" ]; then
  echo "usage: sync-sql-configmap.sh <backend/sql dir> <output file>" >&2
  echo "" >&2
  echo "Refusing to default into infra/k8s/custom-apps/overlays/uat/." >&2
  echo "Migrations are delivered by the migrate-service IMAGE" >&2
  echo "(backend/Dockerfile: COPY sql ./sql), so a ConfigMap there is not" >&2
  echo "applied by ArgoCD and only creates a second source that can drift." >&2
  echo "Name an explicit output path if you are reviving the mount approach." >&2
  exit 2
fi

{
  cat <<'HDR'
# ============================================================
# SQL shipped to the mysql-auto-migrate Job.
# GENERATED by infra/scripts/sync-sql-configmap.sh — do not hand-edit.
# Regenerate after changing anything under backend/sql/.
#
# sync-wave -5 so this exists before the Sync-hook Job (wave 0) mounts it.
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-migrations
  namespace: iiot-uat
  labels:
    app: mysql-migrate
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
HDR
  for f in "$SRC"/*.sql; do
    printf '  %s: |\n' "$(basename "$f")"
    sed 's/^/    /' "$f"
  done
} > "$OUT"

echo "sql configmap → $OUT ($(ls "$SRC"/*.sql | wc -l) files, $(wc -c < "$OUT") bytes)"
