#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Regenerate the mysql-migrations ConfigMap from backend/sql/*.sql.
#
# The migration Job used to `git clone` this repository at run time. That put a
# public-internet round trip on the critical path of every ArgoCD sync: if
# egress was blocked, gitlab.com was slow, or the branch moved, the clone hung
# and the Sync hook never completed — which stalls the ENTIRE application,
# because nothing else applies until the hook reports.
#
# 47KB of SQL fits in a ConfigMap with room to spare, so the files now ship with
# the manifests and the Job only talks to MySQL.
#
# Usage: infra/scripts/sync-sql-configmap.sh /path/to/backend/sql
# ---------------------------------------------------------------------------
set -euo pipefail
SRC="${1:?usage: sync-sql-configmap.sh <backend/sql dir>}"
OUT="$(cd "$(dirname "$0")/../k8s/custom-apps/overlays/uat" && pwd)/mysql-migrations-configmap.yaml"

{
  cat <<'HDR'
# ============================================================
# SQL shipped to the mysql-auto-migrate Job.
# GENERATED by infra/scripts/sync-sql-configmap.sh — do not hand-edit.
# Regenerate after changing anything under backend/sql/.
#
# sync-wave -5 so this exists before the Sync-hook Job (wave 0) mounts it.
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-migrations
  namespace: iiot-uat
  labels:
    app: mysql-migrate
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
data:
HDR
  for f in "$SRC"/*.sql; do
    printf '  %s: |\n' "$(basename "$f")"
    sed 's/^/    /' "$f"
  done
} > "$OUT"

echo "sql configmap → $OUT ($(ls "$SRC"/*.sql | wc -l) files, $(wc -c < "$OUT") bytes)"
