#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Sync the Node-RED flow into GitOps: regenerate the node-red-flow ConfigMap
# from the generated flow JSON and refresh the pod-template checksum annotation
# so ArgoCD rolls the pod (→ load-flow initContainer re-copies the new flow).
#
# Usage: infra/scripts/sync-nodered-flow.sh /path/to/flows.nodered-backend.json
# ---------------------------------------------------------------------------
set -euo pipefail
SRC="${1:?usage: sync-nodered-flow.sh <flows.nodered-backend.json>}"
BASE="$(cd "$(dirname "$0")/../k8s/custom-apps/base" && pwd)"
CM="$BASE/node-red-flow.yaml"
DEP="$BASE/node-red.yaml"

# 1) Regenerate the ConfigMap (flow indented 4 spaces under data.flows.json)
{
  cat <<'HDR'
# ============================================================
# Node-RED flow (GitOps) — the generated backend flow from GitHub
#   backend/node-red/flows.nodered-backend.json
# An initContainer copies this into the PVC /data/flows.json before Node-RED
# starts, so a deploy always runs the committed flow (no manual editor import).
# NOTE: overwrites editor edits on (re)deploy — the generator is the source of
# truth. Regenerate → re-run this script → commit → ArgoCD rolls the pod.
# label app=node-red so the uat overlay moves it to iiot-uat with the pod.
# GENERATED by infra/scripts/sync-nodered-flow.sh — do not hand-edit.
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-red-flow
  namespace: carbon-credit
  labels:
    app: node-red
data:
  flows.json: |
HDR
  sed 's/^/    /' "$SRC"
} > "$CM"

# 2) Refresh the checksum annotation on the pod template
SHA="$(sha256sum "$SRC" | cut -c1-16)"
# GNU sed (Linux/CI runners) — do NOT use BSD `sed -i ''`, which errors on GNU
# sed (treats '' as the script) and silently leaves checksum/flow stale, so the
# pod template never changes and ArgoCD never rolls the new flow.
sed -i -E "s|(checksum/flow: \").*(\")|\1${SHA}\2|" "$DEP"

echo "flow synced → $CM ($(wc -l < "$SRC") lines), checksum/flow=$SHA in $DEP"
