#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Sync the Node-RED flow into GitOps: regenerate the node-red-flow ConfigMap
# from the generated flow JSON and refresh the pod-template checksum annotation
# so ArgoCD rolls the pod (→ load-flow initContainer re-copies the new flow).
#
# Usage: infra/scripts/sync-nodered-flow.sh /path/to/flows.nodered-backend.json
# ---------------------------------------------------------------------------
set -euo pipefail
SRC="${1:?usage: sync-nodered-flow.sh <flows.nodered-backend.json>}"
BASE="$(cd "$(dirname "$0")/../k8s/custom-apps/base" && pwd)"
CM="$BASE/node-red-flow.yaml"
DEP="$BASE/node-red.yaml"

# 1) Regenerate the ConfigMap (flow indented 4 spaces under data.flows.json)
{
  cat <<'HDR'
# ============================================================
# Node-RED flow (GitOps) — the generated backend flow from GitHub
#   backend/node-red/flows.nodered-backend.json
# An initContainer copies this into the PVC /data/flows.json before Node-RED
# starts, so a deploy always runs the committed flow (no manual editor import).
# NOTE: overwrites editor edits on (re)deploy — the generator is the source of
# truth. Regenerate → re-run this script → commit → ArgoCD rolls the pod.
# label app=node-red so the uat overlay moves it to iiot-uat with the pod.
# GENERATED by infra/scripts/sync-nodered-flow.sh — do not hand-edit.
# ============================================================
apiVersion: v1
kind: ConfigMap
metadata:
  name: node-red-flow
  namespace: carbon-credit
  labels:
    app: node-red
  annotations:
    # Server-side apply for THIS resource regardless of how the Application is
    # configured. Client-side apply stores the entire manifest in the
    # kubectl.kubernetes.io/last-applied-configuration annotation, which is
    # capped at 262144 bytes — the flow crossed it and every sync failed with
    #   ConfigMap "node-red-flow" is invalid: metadata.annotations: Too long
    # SSA writes no such annotation, so the ceiling becomes the etcd object
    # limit (~1MB) instead of a quarter of it.
    argocd.argoproj.io/sync-options: ServerSideApply=true
data:
  flows.json: |
HDR
  # Minified, not pretty-printed. The committed JSON stays indented so its diffs
  # are reviewable node by node, but the ConfigMap copy is machine-read only —
  # and the whitespace was ~40% of the bytes that broke the annotation limit.
  node -e 'const fs=require("fs");process.stdout.write("    "+JSON.stringify(JSON.parse(fs.readFileSync(process.argv[1],"utf8")))+"\n")' "$SRC"
} > "$CM"

# Refresh the checksum annotation on the pod template
SHA="$(node -e 'const fs=require("fs"),crypto=require("crypto");console.log(crypto.createHash("sha256").update(fs.readFileSync(process.argv[1])).digest("hex").slice(0,16))' "$SRC")"
sed -i.bak -E "s|(checksum/flow: \").*(\")|\1${SHA}\2|" "$DEP"
rm -f "$DEP.bak"

echo "flow synced → $CM ($(wc -l < "$SRC") lines), checksum/flow=$SHA in $DEP"
